### PR TITLE
API Rewrite: Create a cleaner, more flexible API for IO and processes

### PR DESCRIPTION
**Pull request by scottwittenburg**
So far, only `crop` is supported for raster and pandas datasets.  Other features are missing at the moment as well, including filtering, geo transforms, and dataset writers.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
Sounds fine to me, do you want me to merge it?

**Comment by johnkit** [comment]
Yep, go ahead and merge, Scott. (Or if there's a permission issue, let me and Aashish know.)

**Comment by scottwittenburg** [comment]
I'm just remembering that this would be the first merge to master changing API (and removing much of the functionality), which I think is why I labeled this PR with a `WIP`.  Are we sure we're ready to merge @johnkit and @aashish24?

**Comment by aashish24** [comment]
@scottwittenburg I believe if you have tagged the current master as old-master, then yes, please go ahead remove the WIP and merge it into master :+1:

**Comment by scottwittenburg** [comment]
Yes, it's tagged `master-pre-api-rewrite` for future reference.  I'll merge this.

**Pull request merged**
