### PR TITLE
modified to use conda for install in tests

### PR DESCRIPTION
**Pull request by snowman2**
Initial attempt to trigger builds on Travis-CI.

### CODE REVIEW

**Comment by aashish24** [comment]
@snowman2 thanks for pushing this PR. We can help getting this merged into master @mbertrand

**Comment by snowman2** [comment]
That would be great. The tests passed on my Ubuntu machine (16.04). However, I haven't had time to work on it further to get the build/tests working on Travis and any help to get this working would be appreciated.

**Comment by mbertrand** [comment]
Hi @snowman2, it looks like one of the unit tests is failing:

```
======================================================================
ERROR: test_zonalstats (tests.cases.test_processors.TestGaiaProcessors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/cases/test_processors.py", line 70, in test_zonalstats
    process.compute()
  File "gaia/geo/processes_vector.py", line 1235, in compute
    self.inputs[0].read())
  File "gaia/geo/gdal_functions.py", line 445, in gdal_zonalstats
    return list(gen_zonalstats(zones, raster))
  File "gaia/geo/gdal_functions.py", line 581, in gen_zonalstats
    if hasattr(median, 'data') and not numpy.isnan(median.data):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Is it necessary for conda compatibility to remove the version numbers in requirements.txt?  Pinning the versions of dependencies protects against bugs or incompatibilities in newly released versions, so I'm not very comfortable with getting rid of them.

**Comment by snowman2** [comment]
As seen in the previous commits, installing your code requires removing the pins. I added them back in requirements.txt for reference. There are ways to add pins in the conda_env.yml, but it seems you need to update gaia to use the most recent versions of the packages to be compatible with conda.

**Comment by mbertrand** [comment]
@snowman2 I'm fine with not having pinned versions in setup.py & conda_env.yaml as long as they're still in requirements.txt

For the failing travis test, try replacing [these lines in gdal_functions.gen_zonalstats](https://github.com/snowman2/gaia/blob/conda/gaia/geo/gdal_functions.py#L580-L582) with this:

```
                median = numpy.ma.median(zoneraster)
                if hasattr(median, 'data'):
                    try:
                        properties['median'] = median.data.item()
                    except AttributeError:
                        if median:
                            properties['median'] = median
```

**Comment by snowman2** [comment]
If y'all are interested in testing on windows, I added an appveyor.yml file. For more info: https://www.appveyor.com.

**Comment by snowman2** [comment]
Looks like tests pass. But the flake test fails due to complexity.

**Comment by mbertrand** [comment]
Thanks @snowman2, looks great!  For the failing complexity test, feel free to increase the value of "max-complexity" in the [flake8.cfg](https://github.com/OpenDataAnalytics/gaia/blob/master/tests/flake8.cfg#L5) file to 25 or 30.

**Comment by snowman2** [comment]
Good news: With conda the OSX and linux builds are passing. And you now have tests for python 2.7 and 3.5. Next step, Windows.

**Comment by mbertrand** [comment]
@snowman2 sounds good, would you like us to merge the PR now or wait until the Windows build is in?

**Comment by mbertrand** [comment]
Thanks, @snowman2.  @aashish24 I think this is good to go.  Does kitware have an appveyor account?

**Comment by aashish24** [comment]
> Does kitware have an appveyor account?

No, we do not.

**Comment by aashish24** [comment]
I will create one today @snowman2 @mbertrand

**Comment by aashish24** [comment]
thank you @snowman2 @mbertrand

**Pull request merged**
