### PR TITLE
Initial vagrant/ansible provisioning

### PR DESCRIPTION
**Pull request by kotfic**
Here is some initial provisioning setup with girder and gaia using vagrant and ansible.  To run this make sure you have Virtualbox,  Vagrant,  and ansible==1.9.4  installed  then simply run ```vagrant up```

### CODE REVIEW

**Comment by mbertrand** [comment]
I got this error on OS X with ansible 1.9.4, vagrant 1.7.4, virtualbox 5.0.10:

```
TASK: [Install Gaia as a plugin] **********************************************
<127.0.0.1> REMOTE_MODULE command . /opt/.venv/bin/activate && girder-install plugin -s -f /opt/gaia #USE_SHELL
failed: [gaiavagrant] => {"changed": true, "cmd": ". /opt/.venv/bin/activate && girder-install plugin -s -f /opt/gaia", "delta": "0:00:00.267166", "end": "2016-02-25 22:19:14.100623", "rc": 1, "start": "2016-02-25 22:19:13.833457", "warnings": []}
stderr: Traceback (most recent call last):
  File "/opt/.venv/bin/girder-install", line 9, in <module>
    load_entry_point('girder==1.4.1', 'console_scripts', 'girder-install')()
  File "/opt/girder/girder/utility/install.py", line 211, in main
    parsed.func(parsed)
  File "/opt/girder/girder/utility/install.py", line 108, in install_plugin
    raise Exception('Invalid plugin directory: %s' % pluginPath)
Exception: Invalid plugin directory: /opt/gaia
stdout: Installing gaia...

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/mbertrand/site.retry

gaiavagrant                : ok=70   changed=37   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by aashish24** [comment]
@kotfic are you planning to fix the error?

**Comment by kotfic** [comment]
@aashish24 This is a stupid mistake on my part -  you can set an environment variable to sync the gaia directory on the host with the vagrant box.  If you don't set that variable the script does not install gaia from source and so the provisioning fails.  It is an easy,  but low-priority fix.  I will try to get to it this week.

**Comment by aashish24** [comment]
@kotfic is this ready?

**Comment by jbeezley** [comment]
I had to add a couple of packages to get numpy to build:
```diff
diff --git a/ansible/site.yml b/ansible/site.yml
index 697ecb3..fbff0a0 100644
--- a/ansible/site.yml
+++ b/ansible/site.yml
@@ -55,6 +55,8 @@
       with_items:
         - python-dev
         - libgdal-dev
+        - liblapack-dev
+        - gfortran
       become: yes

     - name: Install Gaia as a plugin
```

**Comment by kotfic** [comment]
This resolves the issue when not launching with ```DEVELOPMENT_SYNC_FOLDERS``` environment variable set.  It also incorporates changes by @jbeezley.  @aashish24  PTAL

**Comment by jbeezley** [comment]
I had to do one other thing to get this to work.  The gaia python package (as opposed to the gaia plugin) needs to be installed for `import gaia` lines to be resolved.  My solution was [this](https://github.com/jbeezley/gaia/blob/aws-deploy/ansible/site.yml#L80-L91).

**Comment by kotfic** [comment]
@jbeezley cef609d should implement the same functionality you pointed to in your branch (while remaining idempotent).  If either you or @aashish24 could review this that would be great

**Comment by kotfic** [comment]
@aashish24 @jbeezley PTAL,  thanks!

**Comment by jbeezley** [comment]
LGTM

**Pull request merged**
