### PR TITLE
ReadTheDocs build fix

### PR DESCRIPTION
**Pull request by mbertrand**
This PR should hopefully allow ReadTheDocs to perform a successful build of the Gaia documentation, by not installing problematic modules depending on pre-installed c libraries (such as gdal).

### CODE REVIEW

**Comment by aashish24** [comment]
@mbertrand our RTD still pointing to old docs. Can we fix it?

**Comment by aashish24** [comment]
other LGTM :+1:

**Comment by aashish24** [comment]
@mbertrand this should fix the RTD.

**Comment by mbertrand** [comment]
@aashish24 I think the RTD setup for gaia will need to be changed, but I don't have permission to do this (not sure who does, I presume you or @jbeezley?).

I forked gaia to my own repo and got RTD to build successfully with the current master branch: http://gaiamb.readthedocs.org/en/latest/

Using the following settings under 'Admin / Advanced Settings':
- Uncheck 'Install your project inside a virtualenv using setup.py install'
- Requirements file: 'docs/requirements.txt'

screen shot 2016-03-01 at 9 47 12 am

**Comment by aashish24** [comment]
@jbeezley owns it. @jbeezley can you fix it?

**Comment by jbeezley** [comment]
Done.  If you give me your, rtd user name I'll add you as a maintainer.

**Comment by mbertrand** [comment]
Thanks!  My rtd username is mbertrand

**Comment by aashish24** [comment]
thanks @jbeezley

**Pull request merged**
